// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afgqiibefhpghhefejgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZ3FpaWJlZmhwZ2hoZWZlamdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjU3ODYsImV4cCI6MjA1ODU0MTc4Nn0.RD1rquA6oGVnpi2U9EyCIhU4Elr9tB8Wdk1Rb6uNljw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);